### PR TITLE
Created Pronunciation View when Ctrl clicked

### PR DESCRIPTION
**Pull request by azvast**

### CODE REVIEW

**Comment by ttop32** [comment]
Thank you for the contribution!

It is interesting feature to use chatgpt as a translator.
But I failed to use this code chatgpt, it says token is expired.
We need to found any auto token renew free chatgpt.

**Comment by azvast** [comment]
We should change the chatgpt using code lines a bit, it's not using public openai library or api.

For the api key, users can import there token in the extension and extension stores the information to localstorage or chrome storage. Or you can create a backend providing an openai translation api.

**Comment by neoOpus** [comment]
> Thank you for the contribution!
> 
> It is interesting feature to use chatgpt as a translator. But I failed to use this code chatgpt, it says token is expired. We need to find any auto token renew free chatgpt.

Most of other extensions use the web version for token but you can also try to use this 


https://api.chatanywhere.org/#/
https://api.chatanywhere.org/v1/oauth/free/github/callback?code=

**Comment by Enlight432** [comment]
> Thank you for the contribution!
> 
> It is interesting feature to use chatgpt as a translator. But I failed to use this code chatgpt, it says token is expired. We need to find any auto token renew free chatgpt.

I tested a lot and Google's artificial intelligence (bard) is **stronger** in translation 

The following extension uses it for translation, maybe it will give you an idea
https://github.com/josStorer/chatGPTBox

**Comment by Johndoe109** [comment]
hello gif

**Pull request closed without merging**
